// Code generated by dockyard; DO NOT EDIT.
//
// TypeScript contract types — the UI-facing half of the Design A codegen
// pipeline (RFC §6.2). Generated from the Go contract structs by github.com/
// gzuidhof/tygo. The Go struct is the single source of truth (P1); regenerate
// with `dockyard generate` and never edit this file by hand.

/**
 * GeneratePodcastInput is the typed input for the generate_podcast tool.
 */
export interface GeneratePodcastInput {
  /**
   * Content is the raw study material to transform into a narrated podcast. Required.
   */
  content: string;
  /**
   * Language is the ISO 639-1 code for the output (e.g. "en", "es", "fr"). Required.
   */
  language: string;
  /**
   * DurationTarget controls approximate output length: "short" (~2 min),
   * "medium" (~5 min), or "long" (~10 min). Optional; defaults to "medium".
   */
  durationTarget?: string;
  /**
   * Tone sets the narration style: "casual", "academic", "enthusiastic", or "calm".
   * Optional; defaults to "casual".
   */
  tone?: string;
  /**
   * Persona is a free-form string that overrides the narrator identity
   * (e.g. "a friendly tutor", "a professor specializing in biology").
   * When set, it takes precedence over Tone. Optional.
   */
  persona?: string;
  /**
   * TopicHint is a short label for the script framing (e.g. "Krebs Cycle").
   * Optional; helps the LLM focus the narration.
   */
  topicHint?: string;
  /**
   * Voice is the TTS voice identifier. Optional; provider-specific default
   * is used when empty.
   */
  voice?: string;
  /**
   * PreviewOnly when true returns the generated script without calling TTS.
   * Useful for reviewing before committing to audio. Optional; defaults to false.
   */
  previewOnly?: boolean;
}
/**
 * GeneratePodcastOutput is the typed output for the generate_podcast tool.
 */
export interface GeneratePodcastOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * Script is the full narration text produced by the LLM.
   */
  script: string;
  /**
   * OutputPath is the absolute path to the generated audio file.
   * Empty when PreviewOnly is true or while the job is still processing.
   */
  outputPath?: string;
  /**
   * JobID identifies the background generation job. Set when PreviewOnly is
   * false; poll list_jobs / read_audio with it. Empty in preview mode.
   */
  jobId?: string;
  /**
   * Status is the job lifecycle state at return time (e.g. "processing").
   * Empty in preview mode.
   */
  status?: string;
  /**
   * WordCount is the number of words in the generated script.
   */
  wordCount: number /* int */;
  /**
   * DurationEstimate is a human-readable approximation (e.g. "~5 min").
   */
  durationEstimate: string;
  /**
   * Language echoes the requested language code.
   */
  language: string;
  /**
   * PreviewOnly echoes the preview flag.
   */
  previewOnly: boolean;
}
/**
 * FlashCard is a single question-answer pair.
 */
export interface FlashCard {
  /**
   * Question is the recall prompt.
   */
  question: string;
  /**
   * Answer is the expected response.
   */
  answer: string;
}
/**
 * GenerateFlashcardsInput is the typed input for the generate_flashcards tool.
 */
export interface GenerateFlashcardsInput {
  /**
   * Content is the raw study material for LLM extraction.
   * Mutually exclusive with Cards. At least one must be provided.
   */
  content?: string;
  /**
   * Cards is a pre-curated list of Q&A pairs. When provided the LLM is
   * skipped entirely. Mutually exclusive with Content.
   */
  cards?: FlashCard[];
  /**
   * Language is the ISO 639-1 code for the cards (e.g. "en", "es").
   * Ignored when Cards is provided. Optional; defaults to "en".
   */
  language?: string;
  /**
   * Difficulty calibrates question depth: "basic" (definition/recall),
   * "intermediate" (comprehension/comparison), or "advanced"
   * (application/synthesis). Ignored when Cards is provided.
   * Optional; defaults to "intermediate".
   */
  difficulty?: string;
  /**
   * CardCount is the number of Q&A pairs to generate (3–40).
   * Ignored when Cards is provided. Optional; defaults to 10.
   */
  cardCount?: number /* int */;
  /**
   * PauseDuration is the seconds of silence between question and answer
   * in the audio output (2–30). Optional; defaults to 5.
   */
  pauseDuration?: number /* int */;
  /**
   * Voice is the TTS voice identifier. Optional.
   */
  voice?: string;
  /**
   * PreviewOnly when true returns the card list without audio synthesis.
   * Optional; defaults to false.
   */
  previewOnly?: boolean;
}
/**
 * GenerateFlashcardsOutput is the typed output for the generate_flashcards tool.
 */
export interface GenerateFlashcardsOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * Cards is the list of generated or provided Q&A pairs.
   */
  cards: FlashCard[];
  /**
   * OutputPath is the absolute path to the generated audio file.
   * Empty when PreviewOnly is true or while the job is still processing.
   */
  outputPath?: string;
  /**
   * JobID identifies the background generation job. Set when PreviewOnly is
   * false; poll list_jobs / read_audio with it. Empty in preview mode.
   */
  jobId?: string;
  /**
   * Status is the job lifecycle state at return time (e.g. "processing").
   * Empty in preview mode.
   */
  status?: string;
  /**
   * CardCount is the actual number of cards in the output.
   */
  cardCount: number /* int */;
  /**
   * DurationEstimate is a human-readable approximation (e.g. "~6 min").
   */
  durationEstimate: string;
  /**
   * Language echoes the language code used for generation.
   */
  language: string;
  /**
   * PreviewOnly echoes the preview flag.
   */
  previewOnly: boolean;
}
/**
 * SynthesizeSpeechInput is the typed input for the synthesize_speech tool.
 * Note: the destination path is owned by the server (a writable OUTPUT_DIR
 * resolved at startup), never supplied by the caller — a caller-chosen path
 * is unreliable across hosts (read-only CWD, non-existent mounts).
 */
export interface SynthesizeSpeechInput {
  /**
   * Text is the exact text to synthesize. May include [PAUSE:N] markers
   * for timed silence (N = seconds). Required.
   */
  text: string;
  /**
   * Voice is the TTS voice identifier. Optional.
   */
  voice?: string;
  /**
   * ResponseFormat selects the audio container: "mp3" or "wav".
   * Optional; defaults to "mp3".
   */
  responseFormat?: string;
}
/**
 * SynthesizeSpeechOutput is the typed output for the synthesize_speech tool.
 */
export interface SynthesizeSpeechOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * OutputPath is the absolute path to the generated audio file.
   * Empty while the job is still processing.
   */
  outputPath?: string;
  /**
   * JobID identifies the background synthesis job; poll list_jobs /
   * read_audio with it.
   */
  jobId?: string;
  /**
   * Status is the job lifecycle state at return time (e.g. "processing").
   */
  status?: string;
  /**
   * CharacterCount is the number of characters sent to the TTS engine
   * (excludes [PAUSE:N] marker text).
   */
  characterCount: number /* int */;
  /**
   * DurationEstimate is a human-readable approximation (e.g. "~3 min").
   */
  durationEstimate: string;
}
/**
 * StudyGuideSection is a single section of the generated study guide.
 */
export interface StudyGuideSection {
  /**
   * Title is the section heading.
   */
  title: string;
  /**
   * Content is the detailed explanation text.
   */
  content: string;
}
/**
 * GenerateStudyGuideInput is the typed input for the generate_study_guide tool.
 */
export interface GenerateStudyGuideInput {
  /**
   * Content is the raw study material to transform into a deep study guide. Required.
   */
  content: string;
  /**
   * Language is the ISO 639-1 code for the output (e.g. "en", "es"). Required.
   */
  language: string;
  /**
   * Difficulty is the target academic level: "undergraduate", "graduate",
   * "masters", or "phd". Controls depth and detail level. Optional; defaults to "graduate".
   */
  difficulty?: string;
  /**
   * DurationTarget controls approximate audio output length: "short" (~5 min),
   * "medium" (~15 min), or "long" (~30 min). Optional; defaults to "medium".
   */
  durationTarget?: string;
  /**
   * Voice is the TTS voice identifier. Optional.
   */
  voice?: string;
  /**
   * PreviewOnly when true returns the study guide text without audio synthesis.
   * Optional; defaults to false.
   */
  previewOnly?: boolean;
}
/**
 * GenerateStudyGuideOutput is the typed output for the generate_study_guide tool.
 */
export interface GenerateStudyGuideOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * Script is the full narrated study guide text.
   */
  script: string;
  /**
   * Sections are the structured sections extracted from the script.
   */
  sections: StudyGuideSection[];
  /**
   * OutputPath is the absolute path to the generated audio file.
   * Empty when PreviewOnly is true or while the job is still processing.
   */
  outputPath?: string;
  /**
   * JobID identifies the background generation job. Set when PreviewOnly is
   * false; poll list_jobs / read_audio with it. Empty in preview mode.
   */
  jobId?: string;
  /**
   * Status is the job lifecycle state at return time (e.g. "processing").
   * Empty in preview mode.
   */
  status?: string;
  /**
   * WordCount is the total word count.
   */
  wordCount: number /* int */;
  /**
   * DurationEstimate is a human-readable approximation (e.g. "~15 min").
   */
  durationEstimate: string;
  /**
   * Language echoes the requested language code.
   */
  language: string;
  /**
   * Difficulty echoes the requested difficulty level.
   */
  difficulty: string;
  /**
   * PreviewOnly echoes the preview flag.
   */
  previewOnly: boolean;
}
/**
 * Job is a single asynchronous audio-generation job, as surfaced to the UI.
 */
export interface Job {
  /**
   * ID is the unique job identifier (pass to read_audio).
   */
  id: string;
  /**
   * Kind is the originating tool: "podcast", "study_guide", "flashcards",
   * or "synthesize".
   */
  kind: string;
  /**
   * Title is a short human-readable label (topic hint or text snippet).
   */
  title: string;
  /**
   * Status is the lifecycle state: "queued", "processing", "completed",
   * or "failed".
   */
  status: string;
  /**
   * CreatedAt is the RFC3339 creation timestamp.
   */
  createdAt: string;
  /**
   * UpdatedAt is the RFC3339 timestamp of the last state change.
   */
  updatedAt: string;
  /**
   * OutputPath is the absolute path to the generated audio file. Set only
   * when Status is "completed".
   */
  outputPath?: string;
  /**
   * DurationEstimate is a human-readable approximation (e.g. "~5 min").
   */
  durationEstimate?: string;
  /**
   * CharacterCount is the number of characters synthesized, when known.
   */
  characterCount?: number /* int */;
  /**
   * WordCount is the script word count, when known.
   */
  wordCount?: number /* int */;
  /**
   * Error is the failure reason. Set only when Status is "failed".
   */
  error?: string;
}
/**
 * ListJobsInput is the (empty) input for the list_jobs tool.
 */
export interface ListJobsInput {
}
/**
 * ListJobsOutput is the typed output for the list_jobs tool.
 */
export interface ListJobsOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * Jobs is the list of all jobs, newest first.
   */
  jobs: Job[];
}
/**
 * Voice is a single TTS voice option for the active provider.
 */
export interface Voice {
  /**
   * ID is the voice identifier passed to the TTS engine.
   */
  id: string;
  /**
   * Label is the human-readable display name.
   */
  label: string;
  /**
   * Description is a short characteristic (e.g. "Warm", "Clear").
   */
  description?: string;
}
/**
 * ListVoicesInput is the (empty) input for the list_voices tool.
 */
export interface ListVoicesInput {
}
/**
 * ListVoicesOutput is the typed output for the list_voices tool.
 */
export interface ListVoicesOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * Provider is the active TTS provider ("gemini" or "openai").
   */
  provider: string;
  /**
   * Model is the configured TTS model id.
   */
  model: string;
  /**
   * DefaultVoice is the voice used when none is specified.
   */
  defaultVoice: string;
  /**
   * Voices are the voices the active provider can speak.
   */
  voices: Voice[];
}
/**
 * ReadAudioInput is the typed input for the read_audio tool. Provide either
 * JobID (preferred) or Path; Path is confined to the server's OUTPUT_DIR.
 */
export interface ReadAudioInput {
  /**
   * JobID is the job whose completed audio to read.
   */
  jobId?: string;
  /**
   * Path is an explicit audio file path under OUTPUT_DIR.
   */
  path?: string;
}
/**
 * ReadAudioOutput is the typed output for the read_audio tool.
 */
export interface ReadAudioOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * DataURI is "data:<mime>;base64,<...>" — the UI converts it to a blob:
   * URL for inline <audio> playback. Empty when Truncated is true.
   */
  dataUri?: string;
  /**
   * Mime is the audio MIME type (e.g. "audio/mpeg").
   */
  mime?: string;
  /**
   * SizeBytes is the file size on disk.
   */
  sizeBytes?: number /* int64 */;
  /**
   * Truncated is true when the file exceeds the inline cap; the UI falls
   * back to showing the OutputPath rather than shipping a huge payload.
   */
  truncated?: boolean;
}
