// Code generated by dockyard; DO NOT EDIT.
//
// TypeScript contract types — the UI-facing half of the Design A codegen
// pipeline (RFC §6.2). Generated from the Go contract structs by github.com/
// gzuidhof/tygo. The Go struct is the single source of truth (P1); regenerate
// with `dockyard generate` and never edit this file by hand.

/**
 * GeneratePodcastInput is the typed input for the generate_podcast tool.
 */
export interface GeneratePodcastInput {
  /**
   * Content is the raw study material to transform into a narrated podcast. Required.
   */
  content: string;
  /**
   * Language is the ISO 639-1 code for the output (e.g. "en", "es", "fr"). Required.
   */
  language: string;
  /**
   * DurationTarget controls approximate output length: "short" (~2 min),
   * "medium" (~5 min), or "long" (~10 min). Optional; defaults to "medium".
   */
  durationTarget?: string;
  /**
   * Tone sets the narration style: "casual", "academic", "enthusiastic", or "calm".
   * Optional; defaults to "casual".
   */
  tone?: string;
  /**
   * Persona is a free-form string that overrides the narrator identity
   * (e.g. "a friendly tutor", "a professor specializing in biology").
   * When set, it takes precedence over Tone. Optional.
   */
  persona?: string;
  /**
   * TopicHint is a short label for the script framing (e.g. "Krebs Cycle").
   * Optional; helps the LLM focus the narration.
   */
  topicHint?: string;
  /**
   * Voice is the TTS voice identifier. Optional; provider-specific default
   * is used when empty.
   */
  voice?: string;
  /**
   * PreviewOnly when true returns the generated script without calling TTS.
   * Useful for reviewing before committing to audio. Optional; defaults to false.
   */
  previewOnly?: boolean;
}
/**
 * GeneratePodcastOutput is the typed output for the generate_podcast tool.
 */
export interface GeneratePodcastOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * Script is the full narration text produced by the LLM.
   */
  script: string;
  /**
   * OutputPath is the absolute path to the generated audio file.
   * Empty when PreviewOnly is true.
   */
  outputPath?: string;
  /**
   * WordCount is the number of words in the generated script.
   */
  wordCount: number /* int */;
  /**
   * DurationEstimate is a human-readable approximation (e.g. "~5 min").
   */
  durationEstimate: string;
  /**
   * Language echoes the requested language code.
   */
  language: string;
  /**
   * PreviewOnly echoes the preview flag.
   */
  previewOnly: boolean;
}
/**
 * FlashCard is a single question-answer pair.
 */
export interface FlashCard {
  /**
   * Question is the recall prompt.
   */
  question: string;
  /**
   * Answer is the expected response.
   */
  answer: string;
}
/**
 * GenerateFlashcardsInput is the typed input for the generate_flashcards tool.
 */
export interface GenerateFlashcardsInput {
  /**
   * Content is the raw study material for LLM extraction.
   * Mutually exclusive with Cards. At least one must be provided.
   */
  content?: string;
  /**
   * Cards is a pre-curated list of Q&A pairs. When provided the LLM is
   * skipped entirely. Mutually exclusive with Content.
   */
  cards?: FlashCard[];
  /**
   * Language is the ISO 639-1 code for the cards (e.g. "en", "es").
   * Ignored when Cards is provided. Optional; defaults to "en".
   */
  language?: string;
  /**
   * Difficulty calibrates question depth: "basic" (definition/recall),
   * "intermediate" (comprehension/comparison), or "advanced"
   * (application/synthesis). Ignored when Cards is provided.
   * Optional; defaults to "intermediate".
   */
  difficulty?: string;
  /**
   * CardCount is the number of Q&A pairs to generate (3–40).
   * Ignored when Cards is provided. Optional; defaults to 10.
   */
  cardCount?: number /* int */;
  /**
   * PauseDuration is the seconds of silence between question and answer
   * in the audio output (2–30). Optional; defaults to 5.
   */
  pauseDuration?: number /* int */;
  /**
   * Voice is the TTS voice identifier. Optional.
   */
  voice?: string;
  /**
   * PreviewOnly when true returns the card list without audio synthesis.
   * Optional; defaults to false.
   */
  previewOnly?: boolean;
}
/**
 * GenerateFlashcardsOutput is the typed output for the generate_flashcards tool.
 */
export interface GenerateFlashcardsOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * Cards is the list of generated or provided Q&A pairs.
   */
  cards: FlashCard[];
  /**
   * OutputPath is the absolute path to the generated audio file.
   * Empty when PreviewOnly is true.
   */
  outputPath?: string;
  /**
   * CardCount is the actual number of cards in the output.
   */
  cardCount: number /* int */;
  /**
   * DurationEstimate is a human-readable approximation (e.g. "~6 min").
   */
  durationEstimate: string;
  /**
   * Language echoes the language code used for generation.
   */
  language: string;
  /**
   * PreviewOnly echoes the preview flag.
   */
  previewOnly: boolean;
}
/**
 * SynthesizeSpeechInput is the typed input for the synthesize_speech tool.
 */
export interface SynthesizeSpeechInput {
  /**
   * Text is the exact text to synthesize. May include [PAUSE:N] markers
   * for timed silence (N = seconds). Required.
   */
  text: string;
  /**
   * OutputPath is the destination file path. Required.
   */
  outputPath: string;
  /**
   * Voice is the TTS voice identifier. Optional.
   */
  voice?: string;
  /**
   * ResponseFormat selects the audio container: "mp3" or "wav".
   * Optional; defaults to "mp3".
   */
  responseFormat?: string;
}
/**
 * SynthesizeSpeechOutput is the typed output for the synthesize_speech tool.
 */
export interface SynthesizeSpeechOutput {
  /**
   * Kind discriminates the output type for the UI dispatcher.
   */
  kind: string;
  /**
   * OutputPath is the absolute path to the generated audio file.
   */
  outputPath: string;
  /**
   * CharacterCount is the number of characters sent to the TTS engine
   * (excludes [PAUSE:N] marker text).
   */
  characterCount: number /* int */;
  /**
   * DurationEstimate is a human-readable approximation (e.g. "~3 min").
   */
  durationEstimate: string;
}
